import {MILK_PRODUCTS} from "../../../database/models/Product/productNames";

export const MILK_CATEGORIES_RESPONSE = {
    PASTERIZOVANNOE: 'pasterizovannoe-moloko',
    ULTRAPASTERIZOVANNOE: 'ultrapasterizovannoe-moloko',
    TOPLENOE: 'toplenoe-moloko',
    STERILIZOVANNOE: 'sterilizovannoe-moloko'
} as const;

export const MILK_CATEGORIES_TRANSIT = {
    [MILK_CATEGORIES_RESPONSE.PASTERIZOVANNOE]: MILK_PRODUCTS.PASTERIZOVANNOE,
    [MILK_CATEGORIES_RESPONSE.ULTRAPASTERIZOVANNOE]: MILK_PRODUCTS.ULTRAPASTERIZOVANNOE,
    [MILK_CATEGORIES_RESPONSE.TOPLENOE]: MILK_PRODUCTS.TOPLENOE,
    [MILK_CATEGORIES_RESPONSE.STERILIZOVANNOE]: MILK_PRODUCTS.STERILIZOVANNOE,
} as const;