import {VEGETABLE_PRODUCTS} from "../../../database/models/Product/productNames";

export const VEGETABLE_CATEGORIES_RESPONSE = {
    TOMATOES: 'tomaty-vegetables',
    CUCUMBERS: 'ogurcy-vegetables',
    PEPPER: 'perec-vegetables',
    POTATO: 'kartoshka-vegetables',
    CARROT: 'morkov-vegetables',
    ONION: 'luk-vegetables',
    BEET: 'svekla-vegetables'
} as const;

export const VEGETABLE_CATEGORIES_TRANSIT = {
    [VEGETABLE_CATEGORIES_RESPONSE.TOMATOES]: VEGETABLE_PRODUCTS.TOMATOES,
    [VEGETABLE_CATEGORIES_RESPONSE.CUCUMBERS]:VEGETABLE_PRODUCTS.CUCUMBERS,
    [VEGETABLE_CATEGORIES_RESPONSE.PEPPER]:VEGETABLE_PRODUCTS.PEPPER,
    [VEGETABLE_CATEGORIES_RESPONSE.POTATO]:VEGETABLE_PRODUCTS.POTATO,
    [VEGETABLE_CATEGORIES_RESPONSE.CARROT]:VEGETABLE_PRODUCTS.CARROT,
    [VEGETABLE_CATEGORIES_RESPONSE.ONION]:VEGETABLE_PRODUCTS.ONION,
    [VEGETABLE_CATEGORIES_RESPONSE.BEET]:VEGETABLE_PRODUCTS.BEET,
} as const;